advertise:
    image: advertise
    build:
      context: ./advertise
      dockerfile: Dockerfile-dev
    container_name: advertise
    volumes:
      - /tmp/advertise/npm-cache:/root/.npm:z
      - ./advertise/src:/usr/src/app/src:z
      - ./advertise/public:/usr/src/app/public:z
    ports:
      - "4007:80"
    environment:
      - PORT=80
    restart: "no"